install:
- gem install asciidoctor

script:
- asciidoctor faq.adoc
env:
  global:
    - GH_REF: github.com/kacimimoghite/testHtmlGenerator.git
    - secure: xeNhDyAxNgn5JGquXewj 
after_success: 
- bash monscript.sh