install:
- gem install asciidoctor

script:
- asciidoctor faq.adoc
env:
  global:
    - GH_REF: github.com/kacimimoghite/testHtmlGenerator.git
    - secure: "<.... encrypted data from above ....>"
after_success: 
- bash monscript.sh