install:
- gem install asciidoctor
script:
- asciidoctor faq.adoc
env:
  global:
  - GH_REF: kacimimoghite/testHtmlGenerator.git

  - secure: pfhZtdyujoHnALx6qWTofqcG4gX3KI8pd3hFJNZuWpPDFnt9vrMoOnoc5IKYKj33RPOV2JzLxvEPwcycQUYOJL0hLDbThlF+3SVxHxtiU5yfIsBtcfNyqvmtimbXPHmkca00b90eDd2PwQg/uTYuWhJLGzfhcB1UhKFhapiSPEF3U0fQUJdH7FbvrS1dLQ+GEYprnZyf5O7AYccDhc8JfgeP0a7Xvko8E0MBbU4bZfSwmnEPeelWQc3ENecWJK0pJThol/kT0IsJvfkvcDj0CKomX3AJn6jxwbs6paX1RBOaq6tzuYzbUMEOHnnQABrjhWSGitMKp3CwVwwQ7vJjsUPu058wDiqNRn+mvA1j0FvLTxbjbn5DwveUA/NZ+QFipfWtGqKqxxUUb7p1JkSGYJstmxKprN9124Sa0WnEzvNIHTWwRU4lzHEHLn4JOgWIGFfDboEAwVz/AUfRWVCar9V3EddctXCckuSzDBPUujsmPtvBtWC4lP+DBdZEA9c3+ZTLCgi1LI8xtHjjNR2B7/NYNJngNfl86yJh4gWAzMhTLvMgqntq8wO2ZG1SBJSRdenLeGCGi5Jckf0QPI/cpOQIL67VcU7TZL8+UD6yYJ7IL/z+B6T4ZCw2iQmomvWmpxqoYtbEsV0tVWSXB7vAya+Sr1Z3PGGpZFgOOal+9nY=

after_success:
- bash monscript.sh

