install:
- gem install asciidoctor
script:
- asciidoctor faq.adoc
env:
  global:
  - GH_REF: kacimimoghite/testHtmlGenerator.git
  - secure: NK4Iz03udDpvQC12QALpohgcPKvmpBiJhzvZjP4NBG36kcfBU8SlqDSnfKVPu7y+b3BBXGQi2PPDxRUh3DcbHYczlkGyFOai/jCxIy4y3grtdUx7IKlGr8H4cMeD8ix2UZ40ABuSroSf4UkKSTmHjnXOhX7rnmleLKezpUdP+QFhNYwvEQnPnsfQ8gl94ZzQwt6Dh7WivtuOcBJl/8k7FTXJM06R1d+uC7RXrC3kjQtccz8EYNt+LlYOA4AnPQkAkPJf87bpeY25l8ZqgEjEE2Wrquo/F0m8xPwmfqBtZvC+BlG67LQbrhNdpVC+8ngjVkdp+4NUeHx+HaWJWvjA5Y6ju/aiJpVp4orYrgJF7LrGiInBpN5O+ZxSxpXhSinVC/zW/ke3U582bF3CLV6ynBGmbti/paNZEta2MUS/8TfQaj+W/gmrf6vuuqf0hdLqmMNLiEAc2xBghQZc6zAwdr/J42cyxor0KxyizS16mkMWqxZIjcnAK0SMZ/I9CzQxdJTWCoqDQoC0/5PeSbubaZyqfQuGEwSj9VWcarEsmrHulIm6Yji8PRGhxQQLJSdlxm75DD02mElc9KXaU/d5Uce9PSR6VmL4a4/VNt4qh6Yh65RFfg+iHOSOjzP3iG6EkJ5+B8h3QkdHrSvw5xId5BgaqMp6X3Kq/XsEs7HOvIk=

after_success:
- bash monscript.sh

